### PR TITLE
Disable preload upon startup

### PR DESCRIPTION
**Pull request by doggogit**
Just in case some rubbish computers can't handle *everything* being preloaded into memory all at once

### CODE REVIEW

**Comment by crowplexus** [comment]
alternatively if someone is stuck at the preload screen, I'd say there could be a way to press some key several times to abort the preload and go to the title directly

**Comment by doggogit** [comment]
> alternatively if someone is stuck at the preload screen, I'd say there could be a way to press some key several times to abort the preload and go to the title directly

Good suggestion 👍

**Comment by MaybeMaru** [comment]
closing since i added a startup warning for preload

**Comment by doggogit** [comment]
I was about to close it 😭

**Pull request closed without merging**
